from GAME_VARIABLES import *

# RED character variables
RED_WIDTH = 64
RED_HEIGHT = 64
RED_VELOCITY = 10
RED_X = 50
RED_Y = 50

# HYDRA character variables
HYDRA_WIDTH = 64
HYDRA_HEIGHT = 64
HYDRA_VELOCITY = 7
HYDRA_X = X//1.2
HYDRA_Y = Y//2

# Eye character variables
EYE_WIDTH = 64
EYE_HEIGHT = 64
EYE_VELOCITY = 7
EYE_X = 300
EYE_Y = 200