from GAME_VARIABLES import *

# RED character variables
RED_WIDTH = 30
RED_HEIGHT = 30
RED_VELOCITY = 10
RED_X = 50
RED_Y = 50

# HYDRA character variables
HYDRA_WIDTH = 64
HYDRA_HEIGHT = 64
HYDRA_VELOCITY = 5
HYDRA_X = X//1.2
HYDRA_Y = Y//2

# Eye character variables
EYE_WIDTH = 64
EYE_HEIGHT = 64
EYE_VELOCITY = 10
EYE_X = 300
EYE_Y = 200
EYE_SIGHT = 10

# Goblin character variables
GOBLIN_WIDTH = 64
GOBLIN_HEIGHT = 64
GOBLIN_VELOCITY = 2
GOBLIN_X = 400
GOBLIN_Y = 300
GOBLIN_SIGHT = 10

# Mushroom character variables
MUSHROOM_WIDTH = 64
MUSHROOM_HEIGHT = 64
MUSHROOM_VELOCITY  = 20
MUSHROOM_X = 500
MUSHROOM_Y = 200
MUSHROOM_SIGHT = 10

# Skeleton character variables
SKELETON_WIDTH = 64
SKELETON_HEIGHT = 64
SKELETON_VELOCITY = 3
SKELETON_X = 700
SKELETON_Y = 300
SKELETON_SIGHT = 10