# RED character variables
RED_WIDTH = 64
RED_HEIGHT = 64
RED_VELOCITY = 7
RED_X = 50
RED_Y = 50

# HYDRA character variables
HYDRA_WIDTH = 64
HYDRA_HEIGHT = 64
HYDRA_VELOCITY = 7
HYDRA_X = 50
HYDRA_Y = 50